<a href="https://colab.research.google.com/github/9terry-student/PyTorch/blob/main/14_%EB%AA%A8%EB%8D%B8_%EC%84%B1%EB%8A%A5_%ED%96%A5%EC%83%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 14장 모델의 성능 향상시키기

## 1. 데이터의 확인과 검증셋

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
import pandas as pd

# 깃허브에 준비된 데이터 호출
!git clone https://github.com/taehojo/data.git

# 와인 데이터 호출
df=pd.read_csv('./data/wine.csv',header=None)

# 데이터 미리 보기
df

fatal: destination path 'data' already exists and is not an empty directory.

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,1
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,1
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,0
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,0
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,0
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,0
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,0

In [12]:
# X: 와인의 속성, y: 와인의 분류
X=df.iloc[:,0:12]
y=df.iloc[:,12]

In [13]:
# 학습셋과 테스트셋 나누기
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True)

# 모델 구조 설정
model=Sequential()
model.add(Dense(30,input_dim=12,activation='relu'))
model.add(Dense(12,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

# 모델 컴파일
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# 모델 실행
history=model.fit(X_train,y_train,epochs=50,batch_size=500,validation_split=0.25) # 0.8 x 0.25 = 0.2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 30)             │           390 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 12)             │           372 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 8)              │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 875 (3.42 KB)

 Trainable params: 875 (3.42 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.2484 - loss: 14.8798 - val_accuracy: 0.2531 - val_loss: 9.9755
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2243 - loss: 6.3569 - val_accuracy: 0.0931 - val_loss: 1.6872
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5953 - loss: 0.8072 - val_accuracy: 0.7469 - val_loss: 0.8217
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7516 - loss: 0.8860 - val_accuracy: 0.7469 - val_loss: 0.9992
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7516 - loss: 0.9491 - val_accuracy: 0.7469 - val_loss: 0.9713
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7516 - loss: 0.8910 - val_accuracy: 0.7469 - val_loss: 0.8788
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7516 - loss: 0.7902 - val_accuracy: 0.7469 - val_loss: 0.7633
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7516 - loss: 0.6767 - val_accuracy: 0.7469 - val_loss: 0.6416
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7519 - loss: 0.5652 - val_accuracy: 0.7515 - val_loss: 0.5230
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7634 - loss: 0.4579 - val_accuracy: 0.7700 - val_loss: 0.4241
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8034 - loss: 0.3793 - val_accuracy: 0.8108 - val_loss: 0.3640
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8386 - loss: 0.3456 - val_accuracy: 0.8408 - val_loss: 0.3514
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8576 - loss: 0.3421 - val_accuracy: 0.8531 - val_loss: 0.3430
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8630 - loss: 0.3282 - val_accuracy: 0.8538 - val_loss: 0.3279
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8630 - loss: 0.3142 - val_accuracy: 0.8577 - val_loss: 0.3177
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8671 - loss: 0.3037 - val_accuracy: 0.8685 - val_loss: 0.3065
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8809 - loss: 0.2919 - val_accuracy: 0.8831 - val_loss: 0.2944
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8912 - loss: 0.2808 - val_accuracy: 0.8900 - val_loss: 0.2840
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8997 - loss: 0.2706 - val_accuracy: 0.8962 - val_loss: 0.2754
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9053 - loss: 0.2627 - val_accuracy: 0.8992 - val_loss: 0.2686
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9107 - loss: 0.2564 - val_accuracy: 0.9069 - val_loss: 0.2628
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9151 - loss: 0.2515 - val_accuracy: 0.9054 - val_loss: 0.2579
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9169 - loss: 0.2468 - val_accuracy: 0.9069 - val_loss: 0.2533
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9222 - loss: 0.2427 - val_accuracy: 0.9092 - val_loss: 0.2490
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9246 - loss: 0.2391 - val_accuracy: 0.9100 - val_loss: 0.2452
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9266 - loss: 0.2353 - val_accuracy: 0.9108 - val_loss: 0.2417
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9281 - loss: 0.2317 - val_accuracy: 0.9123 - val_loss: 0.2382
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9320 - loss: 0.2281 - val_accuracy: 0.9131 - val_loss: 0.2344
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9335 - loss: 0.2241 - val_accuracy: 0.9154 - val_loss: 0.2307
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9348 - loss: 0.2199 - val_accuracy: 0.9185 - val_loss: 0.2268
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9356 - loss: 0.2160 - val_accuracy: 0.9208 - val_loss: 0.2231
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9346 - loss: 0.2127 - val_accuracy: 0.9231 - val_loss: 0.2200
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9358 - loss: 0.2093 - val_accuracy: 0.9246 - val_loss: 0.2186
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9369 - loss: 0.2070 - val_accuracy: 0.9254 - val_loss: 0.2171
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9366 - loss: 0.2053 - val_accuracy: 0.9223 - val_loss: 0.2159
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9379 - loss: 0.2040 - val_accuracy: 0.9223 - val_loss: 0.2149
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9376 - loss: 0.2027 - val_accuracy: 0.9238 - val_loss: 0.2142
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9379 - loss: 0.2016 - val_accuracy: 0.9215 - val_loss: 0.2130
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9382 - loss: 0.2006 - val_accuracy: 0.9223 - val_loss: 0.2119
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9374 - loss: 0.1997 - val_accuracy: 0.9238 - val_loss: 0.2113
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9379 - loss: 0.1988 - val_accuracy: 0.9238 - val_loss: 0.2104
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9387 - loss: 0.1979 - val_accuracy: 0.9238 - val_loss: 0.2095
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9387 - loss: 0.1971 - val_accuracy: 0.9238 - val_loss: 0.2089
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9382 - loss: 0.1964 - val_accuracy: 0.9238 - val_loss: 0.2083
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9394 - loss: 0.1957 - val_accuracy: 0.9246 - val_loss: 0.2078
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9392 - loss: 0.1949 - val_accuracy: 0.9246 - val_loss: 0.2069
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9389 - loss: 0.1943 - val_accuracy: 0.9246 - val_loss: 0.2062
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9387 - loss: 0.1937 - val_accuracy: 0.9254 - val_loss: 0.2062
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9394 - loss: 0.1930 - val_accuracy: 0.9246 - val_loss: 0.2048
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9387 - loss: 0.1921 - val_accuracy: 0.9254 - val_loss: 0.2044

## 2. 모델 업데이트하기

### 기본 코드 불러오기

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 깃허브에 준비된 데이터 호출
!git clone https://github.com/taehojo/data.git

# 와인 데이터 호출
df=pd.read_csv('./data/wine.csv',header=None)

# X: 와인의 속성, y: 와인의 분류
X=df.iloc[:,0:12]
y=df.iloc[:,12]

# 학습셋과 테스트셋 나눔
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True)

# 모델 구조 설정
model=Sequential()
model.add(Dense(30,input_dim=12,activation='relu'))
model.add(Dense(12,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

# 모델 컴파일
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

fatal: destination path 'data' already exists and is not an empty directory.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 30)             │           390 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 12)             │           372 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 8)              │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 875 (3.42 KB)

 Trainable params: 875 (3.42 KB)

 Non-trainable params: 0 (0.00 B)

### 모델의 저장 설정 및 실행

In [18]:
# 모델 저장 조건 설정
modelpath='./data/model/all/{epoch:02d}-{val_accuracy:.4f}.keras'
checkpointer=ModelCheckpoint(filepath=modelpath,verbose=1)

# 모델 실행
history=model.fit(X_train,y_train,epochs=50,batch_size=500,validation_split=0.25,verbose=0,callbacks=[checkpointer])

Epoch 1: saving model to ./data/model/all/01-0.8669.keras

Epoch 1: finished saving model to ./data/model/all/01-0.8669.keras

Epoch 2: saving model to ./data/model/all/02-0.8808.keras

Epoch 2: finished saving model to ./data/model/all/02-0.8808.keras

Epoch 3: saving model to ./data/model/all/03-0.8923.keras

Epoch 3: finished saving model to ./data/model/all/03-0.8923.keras

Epoch 4: saving model to ./data/model/all/04-0.9062.keras

Epoch 4: finished saving model to ./data/model/all/04-0.9062.keras

Epoch 5: saving model to ./data/model/all/05-0.9185.keras

Epoch 5: finished saving model to ./data/model/all/05-0.9185.keras

Epoch 6: saving model to ./data/model/all/06-0.9215.keras

Epoch 6: finished saving model to ./data/model/all/06-0.9215.keras

Epoch 7: saving model to ./data/model/all/07-0.9192.keras

Epoch 7: finished saving model to ./data/model/all/07-0.9192.keras

Epoch 8: saving model to ./data/model/all/08-0.9254.keras

Epoch 8: finished saving model to ./data/model/all/08-0.9254.keras

Epoch 9: saving model to ./data/model/all/09-0.9254.keras

Epoch 9: finished saving model to ./data/model/all/09-0.9254.keras

Epoch 10: saving model to ./data/model/all/10-0.9262.keras

Epoch 10: finished saving model to ./data/model/all/10-0.9262.keras

Epoch 11: saving model to ./data/model/all/11-0.9292.keras

Epoch 11: finished saving model to ./data/model/all/11-0.9292.keras

Epoch 12: saving model to ./data/model/all/12-0.9200.keras

Epoch 12: finished saving model to ./data/model/all/12-0.9200.keras

Epoch 13: saving model to ./data/model/all/13-0.9315.keras

Epoch 13: finished saving model to ./data/model/all/13-0.9315.keras

Epoch 14: saving model to ./data/model/all/14-0.9308.keras

Epoch 14: finished saving model to ./data/model/all/14-0.9308.keras

Epoch 15: saving model to ./data/model/all/15-0.9292.keras

Epoch 15: finished saving model to ./data/model/all/15-0.9292.keras

Epoch 16: saving model to ./data/model/all/16-0.9292.keras

Epoch 16: finished saving model to ./data/model/all/16-0.9292.keras

Epoch 17: saving model to ./data/model/all/17-0.9323.keras

Epoch 17: finished saving model to ./data/model/all/17-0.9323.keras

Epoch 18: saving model to ./data/model/all/18-0.9331.keras

Epoch 18: finished saving model to ./data/model/all/18-0.9331.keras

Epoch 19: saving model to ./data/model/all/19-0.9331.keras

Epoch 19: finished saving model to ./data/model/all/19-0.9331.keras

Epoch 20: saving model to ./data/model/all/20-0.9346.keras

Epoch 20: finished saving model to ./data/model/all/20-0.9346.keras

Epoch 21: saving model to ./data/model/all/21-0.9323.keras

Epoch 21: finished saving model to ./data/model/all/21-0.9323.keras

Epoch 22: saving model to ./data/model/all/22-0.9354.keras

Epoch 22: finished saving model to ./data/model/all/22-0.9354.keras

Epoch 23: saving model to ./data/model/all/23-0.9338.keras

Epoch 23: finished saving model to ./data/model/all/23-0.9338.keras

Epoch 24: saving model to ./data/model/all/24-0.9354.keras

Epoch 24: finished saving model to ./data/model/all/24-0.9354.keras

Epoch 25: saving model to ./data/model/all/25-0.9362.keras

Epoch 25: finished saving model to ./data/model/all/25-0.9362.keras

Epoch 26: saving model to ./data/model/all/26-0.9354.keras

Epoch 26: finished saving model to ./data/model/all/26-0.9354.keras

Epoch 27: saving model to ./data/model/all/27-0.9362.keras

Epoch 27: finished saving model to ./data/model/all/27-0.9362.keras

Epoch 28: saving model to ./data/model/all/28-0.9392.keras

Epoch 28: finished saving model to ./data/model/all/28-0.9392.keras

Epoch 29: saving model to ./data/model/all/29-0.9400.keras

Epoch 29: finished saving model to ./data/model/all/29-0.9400.keras

Epoch 30: saving model to ./data/model/all/30-0.9392.keras

Epoch 30: finished saving model to ./data/model/all/30-0.9392.keras

Epoch 31: saving model to ./data/model/all/31-0.9392.keras

Epoch 31: finished saving model to ./data/model/all/31-0.9392.keras

Epoch 32: saving model to ./data/model/all/32-0.9400.keras

Epoch 32: finished saving model to ./data/model/all/32-0.9400.keras

Epoch 33: saving model to ./data/model/all/33-0.9400.keras

Epoch 33: finished saving model to ./data/model/all/33-0.9400.keras

Epoch 34: saving model to ./data/model/all/34-0.9415.keras

Epoch 34: finished saving model to ./data/model/all/34-0.9415.keras

Epoch 35: saving model to ./data/model/all/35-0.9408.keras

Epoch 35: finished saving model to ./data/model/all/35-0.9408.keras

Epoch 36: saving model to ./data/model/all/36-0.9408.keras

Epoch 36: finished saving model to ./data/model/all/36-0.9408.keras

Epoch 37: saving model to ./data/model/all/37-0.9415.keras

Epoch 37: finished saving model to ./data/model/all/37-0.9415.keras

Epoch 38: saving model to ./data/model/all/38-0.9408.keras

Epoch 38: finished saving model to ./data/model/all/38-0.9408.keras

Epoch 39: saving model to ./data/model/all/39-0.9400.keras

Epoch 39: finished saving model to ./data/model/all/39-0.9400.keras

Epoch 40: saving model to ./data/model/all/40-0.9431.keras

Epoch 40: finished saving model to ./data/model/all/40-0.9431.keras

Epoch 41: saving model to ./data/model/all/41-0.9438.keras

Epoch 41: finished saving model to ./data/model/all/41-0.9438.keras

Epoch 42: saving model to ./data/model/all/42-0.9446.keras

Epoch 42: finished saving model to ./data/model/all/42-0.9446.keras

Epoch 43: saving model to ./data/model/all/43-0.9454.keras

Epoch 43: finished saving model to ./data/model/all/43-0.9454.keras

Epoch 44: saving model to ./data/model/all/44-0.9408.keras

Epoch 44: finished saving model to ./data/model/all/44-0.9408.keras

Epoch 45: saving model to ./data/model/all/45-0.9415.keras

Epoch 45: finished saving model to ./data/model/all/45-0.9415.keras

Epoch 46: saving model to ./data/model/all/46-0.9462.keras

Epoch 46: finished saving model to ./data/model/all/46-0.9462.keras

Epoch 47: saving model to ./data/model/all/47-0.9477.keras

Epoch 47: finished saving model to ./data/model/all/47-0.9477.keras

Epoch 48: saving model to ./data/model/all/48-0.9477.keras

Epoch 48: finished saving model to ./data/model/all/48-0.9477.keras

Epoch 49: saving model to ./data/model/all/49-0.9477.keras

Epoch 49: finished saving model to ./data/model/all/49-0.9477.keras

Epoch 50: saving model to ./data/model/all/50-0.9477.keras

Epoch 50: finished saving model to ./data/model/all/50-0.9477.keras

## 3. 그래프로 과적합 확인하기

In [19]:
# 그래프 확인을 위한 긴 학습
history=model.fit(X_train,y_train,epochs=2000,batch_size=500,verbose=0,validation_split=0.25)

In [20]:
# history에 저장된 학습 결과 확인
hist_df=pd.DataFrame(history.history)
hist_df

      accuracy      loss  val_accuracy  val_loss
0     0.950988  0.137079      0.948462  0.146782
1     0.951245  0.138315      0.949231  0.144504
2     0.951245  0.139220      0.948462  0.140422
3     0.951245  0.133612      0.947692  0.139712
4     0.953297  0.133561      0.948462  0.139636
...        ...       ...           ...       ...
1995  0.993328  0.022610      0.991538  0.062532
1996  0.992815  0.022499      0.988462  0.067190
1997  0.992815  0.025188      0.990769  0.062850
1998  0.993072  0.023770      0.990769  0.062989
1999  0.991789  0.026327      0.989231  0.062136

[2000 rows x 4 columns]