<a href="https://colab.research.google.com/github/9terry-student/PyTorch/blob/main/20_%EC%BA%90%EA%B8%80_%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20장 캐글로 시작하는 새로운 도전

## 3. 학습하기

In [1]:
from tensorflow.keras.models import load_model
import pandas as pd

# 깃허브에 준비된 데이터 호출
!git clone https://github.com/taehojo/data.git

# 캐글에서 내려받은 테스트셋 호출
kaggle_test=pd.read_csv('./data/house_test.csv')
kaggle_test

Cloning into 'data'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 36 (delta 9), reused 26 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 483.12 KiB | 1.94 MiB/s, done.
Resolving deltas: 100% (9/9), done.

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [2]:
# 카테고리형 변수를 0과 1로 이루어진 변수로 변형
kaggle_test=pd.get_dummies(kaggle_test)

# 결측치 대체
kaggle_test=kaggle_test.fillna(kaggle_test.mean())

# 업데이트된 데이터프레임 출력
kaggle_test

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,False,False,False,True,False,False,False,False,True,False
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,False,False,False,True,False,False,False,False,True,False
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,False,False,False,True,False,False,False,False,True,False
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,False,False,False,True,False,False,False,False,True,False
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,False,False,False,True,True,False,False,False,False,False
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,False,False,False,True,True,False,False,False,False,False
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,False,False,False,True,False,False,False,False,True,False
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,False,False,False,True,False,False,False,False,True,False

In [4]:
# 학습에 사용된 열 저장
cols_kaggle=['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']
K_test=kaggle_test[cols_kaggle]

In [6]:
# 15장에서 만든 모델 호출
model=load_model('./data/model/Ch15-house.keras')

# 예측값과 실제값, 실행 번호가 들어갈 빈 리스트 생성
ids=[]

# 25개의 샘플의 실제값, 예측값 출력
Y_prediction=model.predict(K_test).flatten()
for i in range(len(K_test)):
  id=kaggle_test['Id'][i]
  prediction=Y_prediction[i]
  ids.append([id,prediction])

# 테스트 결과의 저장 환경 설정
import time
timestr=time.strftime('%Y%m%d-%H%M%S')
filename=str(timestr)
outdir='./'

# Id와 집 값을 csv 파일로 저장
df=pd.DataFrame(ids,columns=['Id','SalePrice'])
df.to_csv(str(outdir+filename+'_submission.csv'),index=False)

46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step